// Branded, printable plant report. Opens in a new tab and triggers the print
// dialog, where the user can Save as PDF, print, or AirDrop/share it.
import {
  METRICS, PLANTS, displayValue, displayUnit, metricConnected,
  healthScore, rangesForDevice, powerInfo,
} from '../store/helpers';

const esc = (s) => String(s == null ? '' : s).replace(/&/g, '&amp;').replace(/</g, '&lt;').replace(/>/g, '&gt;');

export function openPlantReport({ device, journal = [], weather, settings, user }) {
  const u = settings.units;
  const r = device.reading || {};
  const ranges = rangesForDevice(device);
  const health = healthScore(r, ranges);
  const plant = PLANTS[device.plant] || PLANTS.generic;
  const keys = ['airTemperatureF', 'soilTemperatureF', 'airHumidity', 'soilMoisturePercent'];

  const rows = keys.map((k) => {
    const m = METRICS[k];
    const ok = metricConnected(k, r);
    const vals = (device.history || [])
      .map((h) => h[k])
      .filter((v) => v != null && !(k === 'soilTemperatureF' && v < -100));
    let stats = '—';
    if (ok && vals.length) {
      const min = Math.min(...vals);
      const max = Math.max(...vals);
      const avg = Math.round((vals.reduce((a, b) => a + b, 0) / vals.length) * 10) / 10;
      const unit = displayUnit(m.unit, u);
      stats = `${displayValue(k, min, u)}${unit}  /  ${displayValue(k, avg, u)}${unit}  /  ${displayValue(k, max, u)}${unit}`;
    }
    const now = ok ? `${displayValue(k, r[k], u)}${displayUnit(m.unit, u)}` : 'not connected';
    return `<tr><td>${m.label}</td><td>${now}</td><td>${stats}</td></tr>`;
  }).join('');

  const p = powerInfo(r);
  const power = p.mode === 'ac' ? 'AC power' : `Battery ${p.pct}%${p.charging ? ' (charging)' : ''}`;
  const wx = weather && !weather.error
    ? `${weather.temp}°${u} · ${esc(weather.label)} · ${weather.rainChance}% rain chance · high ${weather.high}°${u}`
    : 'unavailable';

  const entries = (journal || []).slice(0, 6).map((e) => `
      <div class="entry">
        <div class="edate">${new Date(e.date).toLocaleDateString()}</div>
        ${e.photo ? `<img src="${e.photo}" alt=""/>` : ''}
        <div class="etext">${esc(e.text)}</div>
      </div>`).join('');

  const healthColor = health >= 80 ? '#2ecc71' : health >= 55 ? '#f4a52b' : '#ef4444';

  const html = `<!doctype html>
<html><head><meta charset="utf-8"/><title>GrowthPulse report · ${esc(device.name)}</title>
<style>
  body { font-family: -apple-system, BlinkMacSystemFont, 'Segoe UI', Roboto, sans-serif; color: #2c3e50; margin: 36px; }
  .brand b { font-size: 26px; letter-spacing: -0.5px; }
  .brand b span { color: #2ecc71; font-weight: 400; }
  .tag { font-size: 10px; letter-spacing: 2.5px; color: #8a94a0; margin-top: 2px; }
  h1 { font-size: 20px; margin: 26px 0 2px; }
  .sub { color: #6b7280; font-size: 13px; margin-bottom: 16px; }
  .grid { display: flex; gap: 30px; flex-wrap: wrap; margin: 14px 0 4px; }
  .stat .v { font-size: 20px; font-weight: 800; }
  .stat .l { font-size: 10.5px; color: #8a94a0; text-transform: uppercase; letter-spacing: 0.6px; }
  table { border-collapse: collapse; width: 100%; margin: 16px 0; }
  th, td { text-align: left; padding: 8px 10px; border-bottom: 1px solid #e8ebee; font-size: 13px; }
  th { font-size: 11px; text-transform: uppercase; letter-spacing: 0.6px; color: #8a94a0; }
  h2 { font-size: 14px; margin: 22px 0 8px; }
  .entry { border: 1px solid #e8ebee; border-radius: 10px; padding: 10px 12px; margin-bottom: 8px; page-break-inside: avoid; }
  .edate { font-size: 11px; color: #8a94a0; margin-bottom: 4px; }
  .entry img { max-width: 220px; border-radius: 8px; display: block; margin: 6px 0; }
  .etext { font-size: 13px; }
  .foot { margin-top: 28px; font-size: 11px; color: #9aa1aa; border-top: 1px solid #e8ebee; padding-top: 10px; }
</style></head>
<body>
  <div class="brand"><b>Growth<span>Pulse</span></b></div>
  <div class="tag">SMART PLANT MONITORING · PLANT REPORT</div>

  <h1>${esc(device.name)}</h1>
  <div class="sub">${plant.emoji} ${esc(plant.name)}${device.location ? ' · ' + esc(device.location) : ''} · ${power} · prepared for ${esc(user.name)} on ${new Date().toLocaleDateString()}</div>

  <div class="grid">
    <div class="stat"><div class="v" style="color:${healthColor}">${health}/100</div><div class="l">Plant health</div></div>
    <div class="stat"><div class="v">${device.online ? 'Online' : 'Offline'}</div><div class="l">Device status</div></div>
  </div>

  <table>
    <tr><th>Sensor</th><th>Current</th><th>Recent min / avg / max</th></tr>
    ${rows}
  </table>

  <h2>Weather at the plant's home</h2>
  <div style="font-size:13px">${wx}</div>

  ${entries ? `<h2>Growth journal</h2>${entries}` : ''}

  <div class="foot">Generated by GrowthPulse · growthpulsecloud.com</div>
  <script>window.onload = function () { setTimeout(function () { window.print(); }, 350); };</script>
</body></html>`;

  const w = window.open('', '_blank');
  if (!w) return false;
  w.document.write(html);
  w.document.close();
  return true;
}
